import {
  SunIcon,
  CheckCircleIcon,
  FlameIcon,
  NotesIcon,
  CheckCheckIcon,
  HeartIcon,
  TrashIcon,
  FolderIcon,
  FolderOpenIcon,
  CalendarIcon,
  RepeatIcon,
  PlusIcon,
  SearchIcon,
  PinIcon,
  LockIcon,
  MailIcon,
  SortIcon,
  FilterIcon,
  CloseIcon,
  RestoreIcon,
  CheckIcon,
  MenuIcon,
  LogOutIcon,
  GripIcon,
  GridIcon,
  ListIcon,
  SparklesIcon,
  UserIcon,
  ChevronDownIcon,
  ChevronRightIcon,
} from '../components/icons'

export const APP_ICONS = {
  // Views (Structural Line Icons)
  views: {
    today: { icon: SunIcon, label: 'Today', colorClass: 'text-amber-500', emoji: '☀️' },
    allTasks: { icon: CheckCircleIcon, label: 'All Tasks', colorClass: 'text-lavender-accent', emoji: '✅' },
    important: { icon: FlameIcon, label: 'Important', colorClass: 'text-rose-500', emoji: '🔥' },
    notes: { icon: NotesIcon, label: 'Notes', colorClass: 'text-skyblue-accent', emoji: '📝' },
    completed: { icon: CheckCheckIcon, label: 'Completed', colorClass: 'text-emerald-500', emoji: '✅' },
    bucketList: { icon: HeartIcon, label: 'Bucket List', colorClass: 'text-blossom-accent', emoji: '💕' },
    recycleBin: { icon: TrashIcon, label: 'Recycle Bin', colorClass: 'text-ink-muted', emoji: '🗑️' },
  },

  // Priority Levels
  priorities: {
    p0: { label: 'None', shortLabel: 'P0', colorClass: 'text-ink-muted' },
    p1: { label: 'Low', shortLabel: 'P1', colorClass: 'text-skyblue-accent' },
    p2: { label: 'Medium', shortLabel: 'P2', colorClass: 'text-amber-accent' },
    p3: { label: 'Urgent', shortLabel: 'P3', colorClass: 'text-rose-500' },
  },

  // Common UI Icons
  common: {
    folder: FolderIcon,
    folderOpen: FolderOpenIcon,
    calendar: CalendarIcon,
    repeat: RepeatIcon,
    plus: PlusIcon,
    search: SearchIcon,
    pin: PinIcon,
    lock: LockIcon,
    mail: MailIcon,
    sort: SortIcon,
    filter: FilterIcon,
    close: CloseIcon,
    restore: RestoreIcon,
    check: CheckIcon,
    menu: MenuIcon,
    logout: LogOutIcon,
    grip: GripIcon,
    grid: GridIcon,
    list: ListIcon,
    sparkles: SparklesIcon,
    user: UserIcon,
    chevronDown: ChevronDownIcon,
    chevronRight: ChevronRightIcon,
  },
} as const
